spring:
  datasource:
    username: pfvfsoxl
    password: bdXlVLH8pK2LYjj_nHhVODW996cRs3qa
    url: jdbc:postgresql://salt.db.elephantsql.com/pfvfsoxl
    hikari:
      maximum-pool-size: 1
      connectionTestQuery: "SELECT 1"
      connection-timeout: 300000
      idle-timeout: 15000
      max-lifetime: 35000
      validationTimeout: 30000
  jpa:
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "username"
    password: "password"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
project:
  poster: /poster

base:
  url: "http://localhost:8080"
