INSERT INTO MOVIE(movie_id, director, poster, release_year, studio, title) VALUES (99, 'Francis Ford Coppola', 'THE GODFATHER', 1972, 'Paramount', 'The Godfather');
INSERT INTO MOVIE_CAST(movie_movie_id, movie_cast) VALUES (99, 'Marlon Brando, Al Pacino, James Caan, Diane Keaton, Robert Duvall, Lenny Montana');
INSERT INTO MOVIE(movie_id, director, poster, release_year, studio, title) VALUES (98, 'Francis Ford Coppola', 'THE GODFATHER 2', 1974, 'Paramount', 'The Godfather Part 2');
INSERT INTO MOVIE_CAST(movie_movie_id, movie_cast) VALUES (98, 'Robert De Niro, Al Pacino, James Caan, Diane Keaton, Robert Duvall, Lenny Montana');
INSERT INTO MOVIE(movie_id, director, poster, release_year, studio, title) VALUES (97, 'Francis Ford Coppola', 'THE GODFATHER 3', 1975, 'Paramount', 'The Godfather Part 3');
INSERT INTO MOVIE_CAST(movie_movie_id, movie_cast) VALUES (97, 'Al Pacino, James Caan, Sofia Coppola, Robert Duvall, Andy Garcia');
INSERT INTO MOVIE(movie_id, director, poster, release_year, studio, title) VALUES (96, 'Alejandro Jodorowsky', 'TOPO', 1970, 'Independent', 'El Topo');
INSERT INTO MOVIE_CAST(movie_movie_id, movie_cast) VALUES (96, 'Alejandro Jodorowsky, Brontis Jodorowsky');
INSERT INTO MOVIE(movie_id, director, poster, release_year, studio, title) VALUES (95, 'Alejandro Jodorowsky', 'MOUNTAIN', 1973, 'Independent', 'The Holy Mountain');
INSERT INTO MOVIE_CAST(movie_movie_id, movie_cast) VALUES (95, 'Alejandro Jodorowsky, Brontis Jodorowsky');
INSERT INTO MOVIE(movie_id, director, poster, release_year, studio, title) VALUES (94, 'Alejandro Jodorowsky', 'SANGRE', 1989, 'Independent', 'Santa Sangre');
INSERT INTO MOVIE_CAST(movie_movie_id, movie_cast) VALUES (94, 'Alejandro Jodorowsky, Brontis Jodorowsky, Blanca Guerra');
INSERT INTO MOVIE(movie_id, director, poster, release_year, studio, title) VALUES (93, 'Steven Spielberg', 'INDIANA', 1981, 'Paramount', 'Raiders Of The Lost Ark');
INSERT INTO MOVIE_CAST(movie_movie_id, movie_cast) VALUES (93, 'Harrison Ford');
INSERT INTO MOVIE(movie_id, director, poster, release_year, studio, title) VALUES (92, 'Steven Spielberg', 'ET', 1982, 'Paramount', 'E.T. the Extra-Terrestrial');
INSERT INTO MOVIE_CAST(movie_movie_id, movie_cast) VALUES (92, 'Unknown');
INSERT INTO MOVIE(movie_id, director, poster, release_year, studio, title) VALUES (91, 'Steven Spielberg', 'LIST', 1993, 'Paramount', 'The Schindler List');
INSERT INTO MOVIE_CAST(movie_movie_id, movie_cast) VALUES (91, 'Liam Neeson');
INSERT INTO MOVIE(movie_id, director, poster, release_year, studio, title) VALUES (90, 'Steven Spielberg', 'PRIVATE RYAN', 1998, 'Paramount', 'Saving Private Ryan');
INSERT INTO MOVIE_CAST(movie_movie_id, movie_cast) VALUES (90, 'Tom Hanks, Matt Damon');
INSERT INTO MOVIE(movie_id, director, poster, release_year, studio, title) VALUES (89, 'George Lucas', 'EPISODE 4', 1977, 'Twentieth Century Fox', 'Star Wars: Episode IV - A New Hope');
INSERT INTO MOVIE_CAST(movie_movie_id, movie_cast) VALUES (89, 'Mark Hamill, George Lucas, Carrie Fisher, Alec Guiness');
INSERT INTO MOVIE(movie_id, director, poster, release_year, studio, title) VALUES (88, 'George Lucas', 'EPISODE 5', 1980, 'Twentieth Century Fox', 'Star Wars: Episode V - The Empire Strikes Back');
INSERT INTO MOVIE_CAST(movie_movie_id, movie_cast) VALUES (88, 'Mark Hamill, George Lucas, Carrie Fisher, Alec Guiness');
INSERT INTO MOVIE(movie_id, director, poster, release_year, studio, title) VALUES (87, 'George Lucas', 'EPISODE 6', 1983, 'Twentieth Century Fox', 'Star Wars: Episode VI - Return of The Jedi');
INSERT INTO MOVIE_CAST(movie_movie_id, movie_cast) VALUES (87, 'Mark Hamill, George Lucas, Carrie Fisher, Alec Guiness');
INSERT INTO MOVIE(movie_id, director, poster, release_year, studio, title) VALUES (86, 'Ridley Scott', 'ALLIEN', 1979, 'Twentieth Century Fox', 'Alien');
INSERT INTO MOVIE_CAST(movie_movie_id, movie_cast) VALUES (86, 'Sigourney Weaver, Tom Skerritt, John Hurt, Veronica Cartwright');
INSERT INTO MOVIE(movie_id, director, poster, release_year, studio, title) VALUES (85, 'Ridley Scott', 'BLADE', 1982, 'Twentieth Century Fox', 'Blade Runner');
INSERT INTO MOVIE_CAST(movie_movie_id, movie_cast) VALUES (85, 'Harrison Ford, Sean Young, Daryl Hanna');
INSERT INTO MOVIE(movie_id, director, poster, release_year, studio, title) VALUES (84, 'Ridley Scott', 'PROMETHEUS', 2012, 'Twentieth Century Fox', 'Prometheus');
INSERT INTO MOVIE_CAST(movie_movie_id, movie_cast) VALUES (84, 'Charlize Theron, Guy Pearce, Sean Harris');
INSERT INTO MOVIE(movie_id, director, poster, release_year, studio, title) VALUES (83, 'Ridley Scott', 'NAPOLEON', 2023, 'Twentieth Century Fox', 'Napoleon');
INSERT INTO MOVIE_CAST(movie_movie_id, movie_cast) VALUES (83, 'Joaquin Phoenix, Vanessa Kirby, Riana Duce');
INSERT INTO MOVIE(movie_id, director, poster, release_year, studio, title) VALUES (82, 'Martin Scorsese', 'DRIVER', 1976, 'Columbia Pictures', 'Taxi Driver');
INSERT INTO MOVIE_CAST(movie_movie_id, movie_cast) VALUES (82, 'Robert De Niro, Jodie Foster, Cybill Shepherd');
INSERT INTO MOVIE(movie_id, director, poster, release_year, studio, title) VALUES (81, 'Martin Scorsese', 'BULL', 1980, 'Columbia Pictures', 'Raging Bull');
INSERT INTO MOVIE_CAST(movie_movie_id, movie_cast) VALUES (81, 'Robert De Niro, Jodie Foster, Cybill Shepherd');
INSERT INTO MOVIE(movie_id, director, poster, release_year, studio, title) VALUES (80, 'Martin Scorsese', 'TEMPTATION', 1988, 'Columbia Pictures', 'The Last Temptation of Christ');
INSERT INTO MOVIE_CAST(movie_movie_id, movie_cast) VALUES (80, 'Willem Dafoe, Harvey Keitel, Barbara Hershey');
INSERT INTO MOVIE(movie_id, director, poster, release_year, studio, title) VALUES (79, 'Martin Scorsese', 'FELLAS', 1990, 'Columbia Pictures', 'Godfellas');
INSERT INTO MOVIE_CAST(movie_movie_id, movie_cast) VALUES (79, 'Robert De Niro, Ray Liotta, Joe Pesci');
INSERT INTO MOVIE(movie_id, director, poster, release_year, studio, title) VALUES (78, 'Martin Scorsese', 'DEPARTED', 2006, 'Columbia Pictures', 'The Departed');
INSERT INTO MOVIE_CAST(movie_movie_id, movie_cast) VALUES (78, 'Leonardo DiCaprio, Matt Damon, Jack Nicholson');